# Generated by Django 4.2.28 on 2026-02-27 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplitude', '0004_remove_dailydeviceactivity_visit_times'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amplitudesyncschedule',
            name='last_run_on',
        ),
        migrations.RemoveField(
            model_name='amplitudesyncschedule',
            name='run_at',
        ),
        migrations.AddField(
            model_name='amplitudesyncschedule',
            name='last_run_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Последний запуск (время)'),
        ),
    ]
