# Generated by Django 4.2.28 on 2026-03-05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplitude', '0006_bigdatavisit'),
    ]

    operations = [
        migrations.CreateModel(
            name='BigDataPhoneDaySyncState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_normalized', models.CharField(db_index=True, max_length=64, verbose_name='Телефон (normalized)')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('result_count', models.PositiveIntegerField(default=0, verbose_name='Количество визитов за день')),
                ('synced_at', models.DateTimeField(auto_now=True, verbose_name='Синхронизировано в')),
            ],
            options={
                'verbose_name': 'Статус синка BigData (телефон/день)',
                'verbose_name_plural': 'Статусы синка BigData (телефон/день)',
            },
        ),
        migrations.AddConstraint(
            model_name='bigdataphonedaysyncstate',
            constraint=models.UniqueConstraint(fields=('phone_normalized', 'date'), name='uniq_bigdata_phone_day_sync_state'),
        ),
        migrations.AddIndex(
            model_name='bigdataphonedaysyncstate',
            index=models.Index(fields=('date', 'phone_normalized'), name='idx_bigdata_sync_day_phone'),
        ),
    ]
