# Generated by Django 4.2.28 on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplitude', '0007_bigdataphonedaysyncstate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeSiteAccess',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='ID сотрудника')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступ активен')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Доступ сотрудника к сайту',
                'verbose_name_plural': 'Доступы сотрудников к сайту',
                'ordering': ('employee_id',),
            },
        ),
    ]
