# Generated by Django 4.2.28 on 2026-03-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplitude', '0008_employeesiteaccess'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowedEmployeePosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position_guid', models.CharField(db_index=True, max_length=64, unique=True, verbose_name='GUID позиции')),
                ('is_active', models.BooleanField(default=True, verbose_name='Доступ активен')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Разрешенная позиция сотрудника',
                'verbose_name_plural': 'Разрешенные позиции сотрудников',
                'ordering': ('position_guid',),
            },
        ),
        migrations.DeleteModel(
            name='EmployeeSiteAccess',
        ),
    ]
