# Generated by Django 4.2.28 on 2026-09-16 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('amplitude', '0014_remove_allowedemployeeposition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allowedemployeepageaccess',
            name='page',
            field=models.CharField(choices=[('analytics', 'Аналитика'), ('bonus-transactions', 'Транзакция бонусов'), ('coupon-dispatch', 'Отправка купонов'), ('push-dispatch', 'Отправка пушей'), ('blacklist', 'Черный список'), ('guest-profile', 'Профиль гостя'), ('employee-discount-check', 'Проверка скидки сотрудника')], db_index=True, max_length=64, verbose_name='Раздел портала'),
        ),
    ]
