# Generated by Django 4.2.28 on 2026-05-03 19:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BonusTransactionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500, verbose_name='Причина начисления')),
                ('amount', models.PositiveIntegerField(verbose_name='Сумма бонуса')),
                ('start_date', models.DateField(db_index=True, verbose_name='Дата начала действия')),
                ('expiration_date', models.DateField(db_index=True, verbose_name='Дата окончания действия')),
                ('base_id_prefix', models.CharField(blank=True, max_length=255, verbose_name='base_id (префикс)')),
                ('bonus_type', models.PositiveIntegerField(default=1, verbose_name='Тип бонуса (type)')),
                ('registration_bonus', models.BooleanField(default=False, verbose_name='registration_bonus')),
                ('input_source', models.CharField(choices=[('manual', 'Ручной ввод'), ('excel', 'Excel файл'), ('mixed', 'Смешанный')], default='manual', max_length=16, verbose_name='Источник телефонов')),
                ('source_text', models.TextField(blank=True, verbose_name='Телефоны (ручной ввод)')),
                ('source_file', models.FileField(blank=True, null=True, upload_to='bonus_transactions/', verbose_name='Excel файл')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('processing', 'В обработке'), ('completed', 'Завершено'), ('failed', 'Ошибка')], db_index=True, default='pending', max_length=16, verbose_name='Статус')),
                ('total_phones', models.PositiveIntegerField(default=0, verbose_name='Телефонов в исходных данных')),
                ('unique_phones', models.PositiveIntegerField(default=0, verbose_name='Уникальных валидных телефонов')),
                ('guests_found', models.PositiveIntegerField(default=0, verbose_name='Найдено гостей')),
                ('cashbacks_created', models.PositiveIntegerField(default=0, verbose_name='Успешно начислено')),
                ('errors_count', models.PositiveIntegerField(default=0, verbose_name='Ошибок')),
                ('external_api_response', models.JSONField(blank=True, default=dict, verbose_name='Ответ cashback API')),
                ('error_log', models.TextField(blank=True, verbose_name='Лог ошибок')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало обработки')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Конец обработки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bonus_transaction_jobs', to=settings.AUTH_USER_MODEL, verbose_name='Инициатор')),
            ],
            options={
                'verbose_name': 'Задача начисления бонусов',
                'verbose_name_plural': 'Задачи начисления бонусов',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='BonusTransactionJobResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_raw', models.CharField(blank=True, max_length=64, verbose_name='Телефон (как введен)')),
                ('phone_normalized', models.CharField(blank=True, db_index=True, max_length=32, verbose_name='Телефон (normalized)')),
                ('guest_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True, verbose_name='ID гостя')),
                ('doc_guid', models.CharField(blank=True, max_length=64, verbose_name='doc_guid')),
                ('base_id', models.CharField(blank=True, max_length=255, verbose_name='base_id')),
                ('success', models.BooleanField(db_index=True, default=False, verbose_name='Успех')),
                ('error_message', models.TextField(blank=True, verbose_name='Текст ошибки')),
                ('cashback_payload', models.JSONField(blank=True, default=dict, verbose_name='Отправленный payload')),
                ('cashback_response', models.JSONField(blank=True, default=dict, verbose_name='Ответ cashback API')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='bonus_transactions.bonustransactionjob', verbose_name='Задача начисления')),
            ],
            options={
                'verbose_name': 'Результат начисления бонуса',
                'verbose_name_plural': 'Результаты начисления бонусов',
                'ordering': ('id',),
                'indexes': [models.Index(fields=['job', 'success'], name='idx_bonus_job_success')],
            },
        ),
    ]
