name: amplitude_backend_prod

services:
  web:
    build: .
    command: sh /app/entrypoint.sh web-prod
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "127.0.0.1:8001:8000"
    depends_on:
      - db
      - redis

  celery:
    build: .
    command: sh /app/entrypoint.sh celery
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
      - redis

  celery-beat:
    build: .
    command: sh /app/entrypoint.sh beat
    env_file:
      - .env
    restart: unless-stopped
    depends_on:
      - db
      - redis

  db:
    image: postgres:14
    env_file:
      - .env
    restart: unless-stopped
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    restart: unless-stopped

volumes:
  postgres_data:
