"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 4.2.28.
For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-change-me')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = [host.strip() for host in os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',') if host.strip()]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework.authtoken',
    'amplitude',
]

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
}

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.locale.LocaleMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('POSTGRES_DB', 'app_db'),
        'USER': os.getenv('POSTGRES_USER', 'app_user'),
        'PASSWORD': os.getenv('POSTGRES_PASSWORD', 'app_password'),
        'HOST': os.getenv('POSTGRES_HOST', 'db'),
        'PORT': os.getenv('POSTGRES_PORT', '5432'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'ru'

LANGUAGES = [
    ('ru', 'Русский'),
]

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


CELERY_BROKER_URL = os.getenv('CELERY_BROKER_URL', 'redis://redis:6379/0')
CELERY_RESULT_BACKEND = os.getenv('CELERY_RESULT_BACKEND', CELERY_BROKER_URL)
CELERY_BEAT_SCHEDULE = {
    'run-amplitude-sync-hourly': {
        'task': 'amplitude.tasks.run_scheduled_sync',
        'schedule': timedelta(hours=1),
    },
}

AMPLITUDE_API_KEY = os.getenv('AMPLITUDE_API_KEY', '')
AMPLITUDE_SECRET_KEY = os.getenv('AMPLITUDE_SECRET_KEY', '')
AMPLITUDE_EXPORT_URL = os.getenv('AMPLITUDE_EXPORT_URL', 'https://amplitude.com/api/2/export')
AMPLITUDE_TIMEOUT_SECONDS = int(os.getenv('AMPLITUDE_TIMEOUT_SECONDS', '30'))
AMPLITUDE_MOBILE_EVENT_TYPES = [
    event_type.strip()
    for event_type in os.getenv('AMPLITUDE_MOBILE_EVENT_TYPES', '').split(',')
    if event_type.strip()
]

AVATARIYA_BASE_URL = os.getenv('AVATARIYA_BASE_URL', 'http://188.94.158.71/api/v1')
AVATARIYA_BEARER_TOKEN = os.getenv('AVATARIYA_BEARER_TOKEN', '')
AVATARIYA_TIMEOUT_SECONDS = int(os.getenv('AVATARIYA_TIMEOUT_SECONDS', '30'))
AVATARIYA_PHONES_BATCH_SIZE = int(os.getenv('AVATARIYA_PHONES_BATCH_SIZE', '100'))
ALLOWED_EMPLOYEE_POSITION_PATH = os.getenv('ALLOWED_EMPLOYEE_POSITION_PATH', 'p/position/154')
ALLOWED_EMPLOYEE_POSITION_ID = int(os.getenv('ALLOWED_EMPLOYEE_POSITION_ID', '154'))
